Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "lithium"
  config.vm.provider "virtualbox" do |v|
    v.name = "lithium"
  end
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
end
